### ISSUE TITLE
[ldd-img] original_sample_bits

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#135]
Add new item under img:Sampling:

img:original_sample_bits - int, range 1-255, card 0-1
Specifies the number of bits actually acquired by the sensor, before companding or other manipulations.  Contrast this with img:sample_bits, which describes the current state of the image.  Generally in a companded image, sample_bits will be less than original_sample_bits, while in a decompanded image they would be equal.

**Comment by thareUSGS** [comment]
added to v1.8.2.0. Set as same type as sample_bits which is ASCII_Short_String_Collapsed. @rgdeen let me know if original_sample_bits should really be an "int" or ASCII_NonNegative_Integer with a defined min of 1 and max of 255.

**Comment by thareUSGS** [comment]
@rgdeen I plan to close this. do you agree with how this looks?
https://github.com/pds-data-dictionaries/ldd-img/blob/f8ac57adb05eccb9d0860b79ec17c70e7c3b9f94/build/development/3a9c3b61c5b669be2bbc413dd9330c1f52ab5d5e/1.14.0.0/PDS4_IMG_1E00_1820.xsd#L3677

**Comment by rgdeen** [comment]
Yeah that looks good.  In general I just say "int" as opposed to "float" so whichever specific int type is appropriate is fine.  Don't see any need for 0 bits or >255 in my lifetime... ;-)

**Comment by rgdeen** [comment]
Oh I see you defined it as a string, that's the question.  Why would sample_bits have been declared as a string?  Probably because it came out of sample_bit_mask which has to be a string.  So sample_bits is probably a bug.  Too late to change, probably, huh?

I don't much care if you fix the bug on original or stay the same data type as sample_bits for consistency.

**Comment by thareUSGS** [comment]
sample_bits has been around a while. Since it is currently not possible to test a change against "all" existing labels which might use it (that would be a great goal though), I think we will need to keep it a string. Thus I think the original_sample_bits should be defined as the same. Now even though PDS4 can benefit from versioned dictionaries, I think being consistent wins here.

Now in reality, if we did set sample_bits and original_sample_bits to an integer, I doubt it break any workflows... But for now, I will keep it a string. Closing but feel free to respond if you really want the update to sample_bits.

**Comment by rgdeen** [comment]
This apparently did not get merged!!  Although I see the change in the link above, I do not see it in the mainline...

**Comment by thareUSGS** [comment]
It is in the v1820_rebase branch. Needed to wait for GEOM to stabilize as a dependency before pulling a more official "mainline" release.  Which I think for GEOM just happened... I will see if this can be built tomorrow with a release.

**Comment by rgdeen** [comment]
so why is that an issue with this change and not with the other img changes we've done lately?

Or is this the only recent one and I'm thinking about recent changes in other DDs?
