### ISSUE TITLE
[ldd-img_surface] Reachability reference missing!

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#141]
You added the Reachability class but there's no reference to it in any parent class!

Please add as a child of img_surface:Surface_Imaging.

**Comment by thareUSGS** [comment]
Good I need a reason to up the the version. Been trying to create a new release and I've been stuck not being able to override the existing release version. Will fix in the morning.

**Comment by thareUSGS** [comment]
added and new release tagged.
https://github.com/pds-data-dictionaries/ldd-img_surface/releases

I simply added Reachability to the bottom of Surface_Imaging. Since order matters is that okay?
https://github.com/pds-data-dictionaries/ldd-img_surface/blob/21b8072ebd81e62b51ec0fa368682c260c22580a/src/PDS4_IMG_SURFACE_IngestLDD.xml#L995

**Comment by rgdeen** [comment]
Thanks, that should be fine.  I don't care what the order really is, as long as we match.

**Comment by rgdeen** [comment]
I take that back.  Commanded_Parameters should be last by convention.  I don't really care what order it's in above that.  Hope it's not too late to change?

**Comment by rgdeen** [comment]
Actually we already have it between Geometry_Projection and Stereo_Product_Parameters so if you're going to move it anyway... that would be easiest.

**Comment by thareUSGS** [comment]
updated order - new release getting pushed now.
