### ISSUE TITLE
[ldd-cart] Make both attributes of Geographic class required

### ISSUE THREAD

**Issue by wkiri** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#208]
**Describe the issue identified (if applicable)**
The Geographic class contains only two attributes that are both optional.  Therefore, it is possible to end up with an empty class.

**Describe the solution you'd like**
Make both attributes (`latitude_resolution` and `longitude_resolution`) of the Geographic class required.

**Describe alternatives you've considered**
N/A

**LDD Dictionary Version**
1.9.6.0

**PDS4 IM Version**
1.18.0.0

**Need-by Date**
May 20, 2022 to be included in the next IM build.

**Additional context**
DMSP workshop follow-up.

**Comment by thareUSGS** [comment]
updated latitude_resolution and longitude_resolution of the Geographic class to be required.

in v1960 (soon to main): https://github.com/pds-data-dictionaries/ldd-cart/blob/6d5212e9782d4c14ae87af9ccec29e32e7a4f43d/src/PDS4_CART_IngestLDD.xml#L2692

While this was also required by the FGDC metadata the CART namespace [borrowed from](https://www.fgdc.gov/csdgmgraphical/spref/horiz/geogra.htm), I always found it odd to support a "resolution" for vector data (points, lines, polygons). I updated their definitions to try to explain what this means for vector data (spacing between vertices in say a line or polygon). For rasters is more straightforward - simply the pixel spacing in degrees. Although a single resolution in degrees for latitude can also be confusing since on a sphere it shrinks as you go further north from the equator. But the key is that a derived map 2D product in "geographic" (lat/lon), really does need a single resolution (e.g., deg/pixel) for an image. For a global image, this would be the pixel spacing at the equator.
