### ISSUE TITLE
[ldd-rings] Gather column header attributes in a class, Column_Headers

### ISSUE THREAD

**Issue by mseritan** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#305]
**Describe the issue identified (if applicable)**
The Rings dictionary includes attributes that are only used as column headers. We do this to ensure that all column headers that we use are fully described in a dictionary. 

Validate identifies these with a warning that they do not appear in any class. Further, EN has indicated that in order for the Registry to capture information from RMS Node metadata indices, it would help if the column headers used were tied to a specific class. This class will include all of the attributes exclusively used as headers, plus any other attributes that are used as headers.

**Describe the solution you'd like**
We propose a new class, Column_Headers, that contains all attributes used as headers in tables.

**Describe alternatives you've considered**
N/A

**PDS4 IM Version**
1.23

**Need-by Date**
There is no need-by date for this change request.

**Comment by mseritan** [comment]
This Issue corresponds to RMS-DSMP Issue F.

**Comment by matthewtiscareno** [comment]
Yes, this is an issue we have discussed for years.  I don’t want to put these attributes into a class with a name like `Column_Headers`, because that would imply that attributes not in such a class cannot be used as column headers and/or that attributes must be added to this class before people can use them as column headers.

How about if we put them into a class named `Not_Intended_for_Use_in_Labels`?

**Comment by matthewtiscareno** [comment]
This issue duplicates #267.
