### ISSUE TITLE
[ldd-geom] None camera model type

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#54]
So currently there's no way to explicitly say that we don't have a camera model, other than to completely leave off the Camera_Model_Parameters group.  I could go either way on that, but Kate thinks there are use cases beyond 2020 for being able to explicitly say "I don't have a camera model".

In order to do this, we'd need to do the following under Camera_Model_Parameters:

1) add "None" as a valid type for model_type (in the schematron)
2) change minOccurs to 0 in the choice for CAHV/CAHVOR/CAHVORE/PSPH
3) change minOccurs to 0 in the reference frame id choice

In order to preserve validation, you could also add a schematron rule that says absence of the model parameters and reference frame is only valid if the model type is None.

So in the end you'd end up with a paragraph that looks like this:
```
<geom:Camera_Model_Paramaters>
  <model_type>None</model_type>
</>
```
with nothing else in it.

Thoughts?

**Comment by edguinness** [comment]
I am going to put this request aside for now because there is no current case that would use it. I am not sure that we should add a 'none' value for camera model. The PDS4 model is that things are optional so that if they don't apply or are not needed they are left out. We wanted to avoid adding values of none, unknown, or not applicable. In a few cases we allow required items to be nilliable. A better way that would be consistent with the PDS4 approach would be to make model_type nillable.

**Comment by thareUSGS** [comment]
This issue was decided to be not needed (per Ed). Closing.
