### ISSUE TITLE
[ldd-disp] Need to sync LDD DISP v1400 with schema-only DISP release v1500

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#67]
**Issue Type**
The LDD release of DISP was only found at v1400 where as the schema release is at v1500. Updates from v1400 to v1500 can be reviewed here: https://github.com/pds-data-dictionaries/ldd-disp/pull/4/files

**Describe the solution you'd like**
Not only updating the DISP LDD, we need to upgrade to PDS IM 1E00.

**LDD Dictionary Version**
upgrading v1400 to v1500.

**PDS4 IM Version**
1E00 and maybe 1D00

**Comment by thareUSGS** [comment]
from Ed: You may have noticed that the display dictionary 1b00 has both the top level class and the 3 subclasses defined as elements. To me, it makes it confusing how the classes should be used.

**Comment by thareUSGS** [comment]
Trying to back port DISP schema to LDD in this branch. @minhnle this was closer to being done than I remember so with some help here it might be close...
https://github.com/pds-data-dictionaries/ldd-disp/blob/v1500/src/PDS4_DISP_IngestLDD.xml

@edguinness I think I correct the 3 subclasses as elements. Maybe you or @jordanpadams has seen the next error...

I am also getting this build error which I have stared at for 60 minutes and don't understand what it means. It feels like I have run into this before too...
`ERROR Class:  - At least one value for pds:local_reference_type or pds:reference_type must be defined for disp:Display_Settings/pds:Local_Internal_Reference.`  https://github.com/pds-data-dictionaries/ldd-disp/runs/1455327826

**Comment by jordanpadams** [comment]
@thareUSGS @minhnle https://pds-data-dictionaries.github.io/development/ldd-how-to.html#specify-enumerated-values-for-attributes-within-inherited-classes

**Comment by edguinness** [comment]
I believe the error is a result of the new-ish requirement that attributes whose name ends in 'type' have to have at least one enumerated value defined. Check with Mitch because he did something to fix it in the geom dictionary.

**Comment by edguinness** [comment]
Hi Trent,

Here’s an example entry from the geometry ingest_LDD file:

    <DD_Rule>
        <local_identifier>Image_Display_Geometry_0</local_identifier>
        <rule_context>geom:Image_Display_Geometry/pds:Local_Internal_Reference</rule_context>
        <DD_Rule_Statement>
            <rule_type>Assert</rule_type>
            <rule_test>pds:local_reference_type = 'display_to_data_object'
            </rule_test>
            <rule_message>For Local_Internal_Reference in geom:Image_Display_Geometry, local_reference_type must equal 'display_to_data_object'.
            </rule_message>
        </DD_Rule_Statement>
    </DD_Rule>

Cheers,

Mitch


From: Edward A

. Guinness <guinness@wunder.wustl.edu>
Sent: Friday, November 27, 2020 8:49 AM
To: 'pds-data-dictionaries/PDS4-LDD-Issue-Repo' <reply@reply.github.com>
Cc: Mitch Gordon <mgordon@seti.org>; 'Padams, Jordan H (US 398A)' <jordan.h.padams@jpl.nasa.gov>
Subject: RE: [pds-data-dictionaries/PDS4-LDD-Issue-Repo] [ldd-disp] Need to sync LDD DISP v1400 with schema-only DISP release v1500 (#67)

I believe the error is a result of the new-ish requirement that attributes whose name ends in 'type' have to have at least one enumerated value defined. Check with Mitch because he did something to fix it in the geom dictionary.

**Comment by edguinness** [comment]
Hey Mitch,

Has this latest version of the GEOM IngestLDD been submitted to GitHub? If not, and it is ready, can you please send over and I can upload it? That would fix most of Trent's errors.



Jordan

--
Jordan Padams
Engineering Node Manager
Planetary Data System (PDS)
NASA Jet Propulsion Laboratory
jordan.h.padams@jpl.nasa.gov
626.390.9480




-------- Original message --------
From: Mitch Gordon <mgordon@seti.org>
Date: 11/28/20 10:29 AM (GMT-08:00)
To: "Edward A. Guinness" <guinness@wunder.wustl.edu>, 'pds-data-dictionaries/PDS4-LDD-Issue-Repo' <reply@reply.github.com>
Cc: "Padams, Jordan H (US 398A)" <jordan.h.padams@jpl.nasa.gov>
Subject: [EXTERNAL] RE: [pds-data-dictionaries/PDS4-LDD-Issue-Repo] [ldd-disp] Need to sync LDD DISP v1400 with schema-only DISP release v1500 (#67)

Hi Trent,

Here’s an example entry from the geometry ingest_LDD file:

    <DD_Rule>
        <local_identifier>Image_Display_Geometry_0</local_identifier>
        <rule_context>geom:Image_Display_Geometry/pds:Local_Internal_Reference</rule_context>
        <DD_Rule_Statement>
            <rule_type>Assert</rule_type>
            <rule_test>pds:local_reference_type = 'display_to_data_object'
            </rule_test>
            <rule_message>For Local_Internal_Reference in geom:Image_Display_Geometry, local_reference_type must equal 'display_to_data_object'.
            </rule_message>
        </DD_Rule_Statement>
    </DD_Rule>

Cheers,

Mitch


From: Edward A

. Guinness <guinness@wunder.wustl.edu>
Sent: Friday, November 27, 2020 8:49 AM
To: 'pds-data-dictionaries/PDS4-LDD-Issue-Repo' <reply@reply.github.com>
Cc: Mitch Gordon <mgordon@seti.org>; 'Padams, Jordan H (US 398A)' <jordan.h.padams@jpl.nasa.gov>
Subject: RE: [pds-data-dictionaries/PDS4-LDD-Issue-Repo] [ldd-disp] Need to sync LDD DISP v1400 with schema-only DISP release v1500 (#67)

I believe the error is a result of the new-ish requirement that attributes whose name ends in 'type' have to have at least one enumerated value defined. Check with Mitch because he did something to fix it in the geom dictionary.

**Comment by thareUSGS** [comment]
thanks for all the help. I think I can call this ready for 1.F.0.0. @minhnle and still need to check if back-porting worked. Just need to diff schema from build: https://github.com/pds-data-dictionaries/ldd-disp/tree/v1500/build/development/46ba0e84c7f370714bd1adc0b81a44f60a711866/1.14.0.0

to original schema: https://github.com/pds-data-dictionaries/ldd-disp/tree/v1500/build/release/1.B.0.0_1.4.0.0
