### ISSUE TITLE
[BUILD REQUEST] IMG LDD Version:1.8.0.0 IM Version:1.E.0.0

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#91]
I am having build issues with IMG that I can't figure out.
https://github.com/pds-data-dictionaries/ldd-img/actions/runs/226129718

I'm not sure how to track that issue down. It validates in oxygen and builds using Lddtool locally.

**Comment by rgdeen** [comment]
I'd be happy if you wanted to email me all the locally built xsd/sch/json in the meantime until this is fixed....  ;-)

**Comment by jordanpadams** [comment]
@thareUSGS i will see what I can do. One note though, it looks like you have a pretty narly backlog of PRs and merge requests in your branches. once we get this figured out. i would highly recommend getting back synced up with master.

**Comment by jordanpadams** [comment]
https://github.com/pds-data-dictionaries/ldd-img/compare/v1800

**Comment by jordanpadams** [comment]
I checked out your branch and did a [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) with master. your branch was using an old version of the CI/CD software that had been upgraded since you started working. sorry about that! the perks of working in simultaneous development :-)

https://github.com/pds-data-dictionaries/ldd-img/pull/84
https://github.com/pds-data-dictionaries/ldd-img/runs/1034241054?check_suite_focus=true

**Comment by jordanpadams** [comment]
@thareUSGS ⬆️
